#
# Makefile for hooks
#

obj-$(CONFIG_SWAP_HOOK_TASKDATA) += taskdata.o
obj-$(CONFIG_SWAP_HOOK_USAUX) += userspace_aux.o
obj-$(CONFIG_SWAP_HOOK_SYSCALL) += syscall.o
obj-$(CONFIG_SWAP_HOOK_SWITCH_TO) += switch_to.o
obj-$(CONFIG_SWAP_HOOK_ENERGY) += energy.o
obj-$(CONFIG_SWAP_HOOK_FILE_OPS) += file_ops.o
obj-$(CONFIG_SWAP_HOOK_SIGNAL) += signal.o
