#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_DRV_MAX8997)		+= max8997_vibrator.o
obj-$(CONFIG_MOTOR_DRV_MAX77803)	+= max77803_haptic.o
obj-$(CONFIG_MOTOR_DRV_ISA1200)		+= isa1200_vibrator.o
obj-$(CONFIG_MOTOR_DRV_ISA1400)		+= isa1400_vibrator.o
obj-$(CONFIG_MOTOR_DRV_ISA1000A)	+= isa1000a_vibrator.o
obj-$(CONFIG_HAPTIC_ISA1200)			+= haptic_isa1200.o
obj-$(CONFIG_HAPTIC_ISA1400)			+= haptic_isa1400.o
obj-$(CONFIG_HAPTIC)				+= haptic.o
obj-$(CONFIG_DC_MOTOR)			+= dc_motor.o
obj-$(CONFIG_MOTOR_INFO)	+= motor_info.o
obj-$(CONFIG_FF_DC_VIBRATOR)	+= ff_dc_vibrator.o
obj-$(CONFIG_MOTOR_DRV_DRV2624)		+= drv2624.o
obj-$(CONFIG_MOTOR_DRV_ZH915)		+= zh915.o
