#
# Makefile for trace.
#

obj-$(CONFIG_EXYNOS_ITM) += exynos7570-itm.o
obj-$(CONFIG_EXYNOS_SNAPSHOT) += exynos-ss.o
obj-$(CONFIG_EXYNOS_CORESIGHT) += exynos-coresight.o
obj-$(CONFIG_EXYNOS_CORESIGHT_ETM) += exynos-coresight-etm.o
obj-$(CONFIG_EXYNOS_CORESIGHT_STM) += of_coresight.o coresight.o coresight-stm.o
obj-$(CONFIG_EXYNOS_DRAMTEST) += dramtest.o
obj-$(CONFIG_SYSTEM_LOAD_ANALYZER) += load_analyzer.o
obj-$(CONFIG_SLUGGISH_ANALYZER)	+= sluggish_analyzer.o
