/*
 * /battery/s2mpw01_charger.h
 *
 * Header of S2MPW01 Charger Driver
 *
 * Copyright (C) 2015 Samsung Electronics
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef S2MPW01_CHARGER_H
#define S2MPW01_CHARGER_H
#include <linux/mfd/samsung/s2mpw01.h>
#include <linux/mfd/samsung/s2mpw01-private.h>

#define MASK(width, shift)      (((0x1 << (width)) - 1) << shift)

#define S2MPW01_CHG_REG_INT1		0x00
#define S2MPW01_CHG_REG_INT2		0x01
#define S2MPW01_CHG_REG_INT3		0x02
#define S2MPW01_CHG_REG_INT1M		0x03
#define S2MPW01_CHG_REG_INT2M		0x04
#define S2MPW01_CHG_REG_INT3M		0x05
#define S2MPW01_CHG_REG_STATUS1		0x06
#define S2MPW01_CHG_REG_STATUS2		0x07
#define S2MPW01_CHG_REG_STATUS3		0x08
#define S2MPW01_CHG_REG_CTRL1       0x09
#define S2MPW01_CHG_REG_CTRL2       0x0A
#define S2MPW01_CHG_REG_CTRL3       0x0B
#define S2MPW01_CHG_REG_CTRL4       0x0C
#define S2MPW01_CHG_REG_CTRL5       0x0D
#define S2MPW01_CHG_REG_CTRL6       0x0E
#define S2MPW01_CHG_REG_CTRL7       0x0F
#define S2MPW01_CHG_REG_CTRL8       0x10
#define S2MPW01_CHG_REG_CTRL9		0x11


/* S2MPW01_CHG_STATUS1 */
#define CHG_STATUS1_RE_CHG	0
#define CHG_STATUS1_CHG_DONE 1
#define CHG_STATUS1_TOP_OFF	2
#define	CHG_STATUS1_PRE_CHG	3
#define CHG_STATUS1_CHG_STS	4
#define CHG_STATUS1_CIN2BAT	5
#define CHG_STATUS1_CHGVINOVP 6
#define CHG_STATUS1_CHGVIN	7

#define CHGVINOVP_STATUS_SHIFT	6
#define CHGVINOVP_STATUS_MASK	BIT(CHGVINOVP_STATUS_SHIFT)
#define CIN2BAT_STATUS_SHIFT	5
#define CIN2BAT_STATUS_MASK	BIT(CIN2BAT_STATUS_SHIFT)
#define CHGSTS_STATUS_SHIFT	4
#define CHGSTS_STATUS_MASK	BIT(CHGSTS_STATUS_SHIFT)
#define TOP_OFF_STATUS_SHIFT    2
#define TOP_OFFSTATUS_MASK      BIT(TOP_OFF_STATUS_SHIFT)

/* S2MPW01_CHG_STATUS2 */
#define UART_BOOT_OFF_STATUS_SHIFT      0
#define UART_BOOT_OFF_STATUS_MASK       BIT(UART_BOOT_OFF_STATUS_SHIFT)
#define USB_BOOT_ON_STATUS_SHIFT        1
#define USB_BOOT_ON_STATUS_MASK BIT(USB_BOOT_ON_STATUS_SHIFT)
#define USB_BOOT_OFF_STATUS_SHIFT       2
#define USB_BOOT_OFF_STATUS_MASK        BIT(USB_BOOT_OFF_STATUS_SHIFT)
#define JIGON_STATUS_SHIFT      3
#define JIGON_STATUS_MASK       BIT(JIGON_STATUS_SHIFT)
#define AD_PATH_STATUS_SHIFT    4
#define AD_PATH_STATUS_MASK     BIT(AD_PATH_STATUS_SHIFT)
#define FCHG_STATUS_SHIFT       5
#define FCHG_STATUS_MASK        BIT(FCHG_STATUS_SHIFT)
#define CHGIN_INPUT_STATUS_SHIFT        6
#define CHGIN_INPUT_STATUS_MASK BIT(CHGIN_INPUT_STATUS_SHIFT)
#define DET_BAT_STATUS_SHIFT    7
#define DET_BAT_STATUS_MASK     BIT(DET_BAT_STATUS_SHIFT)

/* S2MPW01_CHG_STATUS3 */
#define CVOK_STATUS_SHIFT       0
#define CVOK_STATUS_MASK        BIT(CVOK_STATUS_SHIFT)
#define UART_CABLE_STATUS_SHIFT 1
#define UART_CABLE_STATUS_MASK  BIT(UART_CABLE_STATUS_SHIFT)
#define FACT_LEAKAGE_STATUS_SHIFT       2
#define FACT_LEAKAGE_STATUS_MASK        BIT(FACT_LEAKAGE_STATUS_SHIFT)
#define UART_BOOT_ON_STATUS_SHIFT       3
#define UART_BOOT_ON_STATUS_MASK        BIT(UART_BOOT_ON_STATUS_SHIFT)
#define TMROUT_STATUS_SHIFT     4
#define TMROUT_STATUS_MASK      BIT(TMROUT_STATUS_SHIFT)
#define CHGTSD_STATUS_SHIFT     5
#define CHGTSD_STATUS_MASK      BIT(CHGTSD_STATUS_SHIFT)
#define MRSTB_STATUS_SHIFT      6
#define MRSTB_STATUS_MASK       BIT(MRSTB_STATUS_SHIFT)
#define WDT_STATUS_SHIFT        7
#define WDT_STATUS_MASK BIT(WDT_STATUS_SHIFT)


/* S2MPW01_CHG_CTRL1 */
#define EN_CHG_SHIFT		7
#define EN_CHG_MASK		BIT(EN_CHG_SHIFT)

/* S2MPW01_CHG_CTRL2 */
#define FAST_CHARGING_CURRENT_SHIFT	1
#define FAST_CHARGING_CURRENT_WIDTH	3
#define FAST_CHARGING_CURRENT_MASK	MASK(FAST_CHARGING_CURRENT_WIDTH,\
					FAST_CHARGING_CURRENT_SHIFT)

/* S2MPW01_CHG_CTRL4 */
#define FIRST_TOPOFF_CURRENT_SHIFT	4
#define FIRST_TOPOFF_CURRENT_WIDTH	4
#define FIRST_TOPOFF_CURRENT_MASK	MASK(FIRST_TOPOFF_CURRENT_WIDTH,\
					FIRST_TOPOFF_CURRENT_SHIFT)
#define SET_VIN_DROP_SHIFT	1
#define SET_VIN_DROP_WIDTH	3
#define SET_VIN_DROP_MASK	MASK(SET_VIN_DROP_WIDTH, SET_VIN_DROP_SHIFT)


/* S2MPW01_CHG_CTRL5 */
#define SET_VF_VBAT_SHIFT	1
#define SET_VF_VBAT_WIDTH	3
#define SET_VF_VBAT_MASK	MASK(SET_VF_VBAT_WIDTH, SET_VF_VBAT_SHIFT)

#define SET_ADD_ON_SHIFT	5
#define SET_ADD_ON_WIDTH	1
#define SET_ADD_ON_MASK	MASK(SET_ADD_ON_WIDTH, SET_ADD_ON_SHIFT)


/* S2MPW01_CHG_CTRL7 */
#define SET_ADD_PATH_SHIFT	0
#define SET_ADD_PATH_WIDTH	8
#define SET_ADD_PATH_MASK	MASK(SET_ADD_PATH_WIDTH, SET_ADD_PATH_SHIFT)

/* S2MPW01_CHG_CTRL8 */
#define NO_TIMEOUT_30M_SHIFT	2
#define NO_TIMEOUT_30M_MASK	BIT(NO_TIMEOUT_30M_SHIFT)

#define FAKE_BAT_LEVEL                  50

enum {
	CHG_REG = 0,
	CHG_DATA,
	CHG_REGS,
};

struct charger_info {
	int dummy;
};

#endif /*S2MPW01_CHARGER_H*/
