#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SENSORS_SSP_BMI168)	+= accel_bmi168.o gyro_bmi168.o
obj-$(CONFIG_SENSORS_SSP_MPU6500)	+= accel_mpu6500.o gyro_mpu6500.o
obj-$(CONFIG_SENSORS_SSP_MPU9250)	+= accel_mpu9250.o gyro_mpu9250.o magnetic_mpu9250.o
obj-$(CONFIG_SENSORS_SSP_ICM20628)	+= accel_icm20628.o gyro_icm20628.o
obj-$(CONFIG_SENSORS_SSP_K6DS3TR)	+= accel_k6ds3tr.o gyro_k6ds3tr.o
obj-$(CONFIG_SENSORS_SSP_LSM6DSL)	+= accel_lsm6dsl.o gyro_lsm6dsl.o
obj-$(CONFIG_SENSORS_SSP_AK09911)	+= magnetic_ak09911.o
obj-$(CONFIG_SENSORS_SSP_YAS537)	+= magnetic_yas537.o
obj-$(CONFIG_SENSORS_SSP_LPS25H)	+= pressure_lps25h.o
obj-$(CONFIG_SENSORS_SSP_TSL2584)	+= light_tsl2584.o
obj-$(CONFIG_SENSORS_SSP_CM3323)	+= light_cm3323.o
obj-$(CONFIG_SENSORS_SSP_SHTW1)	+= temphumidity_shtw1.o
obj-$(CONFIG_SENSORS_SSP_AD45251)	+= hrm_ad45251.o
obj-$(CONFIG_SENSORS_SSP_PPS960)	+= hrm_pps960.o
obj-$(CONFIG_SENSORS_SSP_MAX86902)	+= hrm_max86902.o uv_max86902.o
obj-$(CONFIG_SENSORS_SSP_HM121)	+= gsr_hm121.o
obj-$(CONFIG_SENSORS_SSP_ADS1292)	+= ecg_ads1292.o
obj-$(CONFIG_SENSORS_SSP_SX9310)	+= grip_sx9310.o
